### ISSUE TITLE
Brainstorm para indicações de ideias em projetos de software

### ISSUE THREAD

**Issue by radamesp7** [radamesp7/AbexII_G10_2024#1]
O brainstorming se aplica a disciplina de aprendizado baseado em experiências, onde os alunos em grupos indicam o que pode ser uma ideia de problema que possa ser solucionado com o desenvolvimento de um aplicativo de software e que tem uma finalidade prática. O brainstoriming deve gerar ideias entre os membros do grupo e precisa que se use como base o github para que possam trabalhar como grupo de trabalho e registrar as ideias conforme forem gerando as mesmas.

 Lista de Ideias:

**Comment by GustavoAlderi** [comment]
Rastreamento de transporte público para chapecó, possibilitando chamadas para a polícia rápidas e monitoramento da localização do transporte pelo passageiro.

**Comment by Rafamkk0** [comment]
Software para calculo de previsao de entrega para fretes de transportadoras, junto com realizaçao de orçamento calculando de acordo com peso, valor de nf etc

**Comment by GustavoAlderi** [comment]
Software para identificação de possibilidade de plantio no solo escolhido.

**Comment by Rafamkk0** [comment]
software para melhor de corte de pepino

**Comment by GustavoAlderi** [comment]
Software para identificação de nutrientes presentes em refeições.

**Comment by Rafamkk0** [comment]
aplicativo que auxilia a preparação de alimentos, por exemplo informando a quantidade de agua para tanto de arroz, e o tempo necessario
